services:
  web: 
    build:
      context: app
    command: gunicorn demo.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./app/:/usr/src/app
      - staticfiles:/usr/src/app/staticfiles
    ports: 
      - '8000:8000'
    env_file:
      - ./.env.dev.env
    
volumes:
  static_files:
